apiVersion: v1
kind: Secret
metadata:
  name: aacp-mtls-client-intent
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_CLIENT_CERT>
  tls.key: <BASE64_CLIENT_KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: aacp-mtls-client-permit
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_CLIENT_CERT>
  tls.key: <BASE64_CLIENT_KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: aacp-mtls-ca-internal
type: Opaque
data:
  ca.crt: <BASE64_CA_CERT>
