apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fault-block-kafka-egress
  namespace: aacp
spec:
  podSelector:
    matchLabels:
      app: kafka-interceptor
  policyTypes: [Egress]
  egress:
    # allow DNS only; deny broker
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
