apiVersion: v1
kind: ServiceAccount
metadata:
  name: aacp-cert-rotation
  namespace: aacp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aacp-cert-rotation
  namespace: aacp
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","patch"]
  - apiGroups: ["apps"]
    resources: ["deployments","statefulsets"]
    verbs: ["get","patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale","statefulsets/scale"]
    verbs: ["get","patch"]
  - apiGroups: ["apps"]
    resources: ["deployments","statefulsets"]
    verbs: ["update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aacp-cert-rotation
  namespace: aacp
subjects:
  - kind: ServiceAccount
    name: aacp-cert-rotation
    namespace: aacp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aacp-cert-rotation
