listeners=SSL://0.0.0.0:9093
advertised.listeners=SSL://kafka:9093
security.inter.broker.protocol=SSL
ssl.keystore.location=/etc/kafka/secrets/broker.keystore.jks
ssl.keystore.password=${KAFKA_KEYSTORE_PASSWORD}
ssl.key.password=${KAFKA_KEY_PASSWORD}
ssl.truststore.location=/etc/kafka/secrets/broker.truststore.jks
ssl.truststore.password=${KAFKA_TRUSTSTORE_PASSWORD}
ssl.client.auth=required
authorizer.class.name=kafka.security.authorizer.AclAuthorizer
allow.everyone.if.no.acl.found=false
super.users=User:CN=broker
