apiVersion: v1
kind: Secret
metadata:
  name: bl19-mtls-client
type: kubernetes.io/tls
data:
  # base64 of PEMs
  tls.crt: <BASE64_CLIENT_CERT>
  tls.key: <BASE64_CLIENT_KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: bl19-mtls-ca
type: Opaque
data:
  ca.crt: <BASE64_CA_CERT>
